use crossterm::event::{KeyCode, KeyEvent, KeyEventKind, KeyModifiers};

#[derive(Clone)]
pub enum Action {
    Quit,
    MoveUp,
    MoveDown,
    CollapseOrParent,
    ExpandOrChild,
    EnterFullPreview,
    ExitFullPreview,
    PreviewPrev,
    PreviewNext,
    SelectPreviewPane,
    Select,
    Kill,
    ConfirmKill,
    CancelKill,
    Refresh,
    TogglePin,
    MovePinUp,
    MovePinDown,
    EnterFilter,
    FilterChar(char),
    FilterBackspace,
    FilterDeleteForward,
    FilterKillWord,
    FilterKillLine,
    FilterKillLineForward,
    FilterCursorLeft,
    FilterCursorRight,
    FilterCursorWordLeft,
    FilterCursorWordRight,
    FilterCursorStart,
    FilterCursorEnd,
    SelectIndex(usize),
    ExitFilter,
    StartRename,
    RenameChar(char),
    RenameBackspace,
    RenameDeleteForward,
    RenameKillWord,
    RenameKillLine,
    RenameKillLineForward,
    RenameCursorLeft,
    RenameCursorRight,
    RenameCursorWordLeft,
    RenameCursorWordRight,
    RenameCursorStart,
    RenameCursorEnd,
    ConfirmRename,
    CancelRename,
    None,
}

#[derive(Clone, PartialEq)]
pub enum Mode {
    Normal,
    Confirming,
    Filtering,
    Previewing,
    Renaming,
}

pub fn map_key(key: KeyEvent, mode: &Mode) -> Action {
    if key.kind != KeyEventKind::Press {
        return Action::None;
    }

    match mode {
        Mode::Normal => match (key.code, key.modifiers) {
            (KeyCode::Char('q'), _) | (KeyCode::Esc, _) => Action::Quit,
            (KeyCode::Char('k'), KeyModifiers::NONE) | (KeyCode::Up, KeyModifiers::NONE) => Action::MoveUp,
            (KeyCode::Char('p'), KeyModifiers::CONTROL) => Action::MoveUp,
            (KeyCode::Char('j'), KeyModifiers::NONE) | (KeyCode::Down, KeyModifiers::NONE) => Action::MoveDown,
            (KeyCode::Char('n'), KeyModifiers::CONTROL) => Action::MoveDown,
            (KeyCode::Char('h'), _) | (KeyCode::Left, _) => Action::CollapseOrParent,
            (KeyCode::Char('l'), _) | (KeyCode::Right, _) => Action::ExpandOrChild,
            (KeyCode::Char(' '), _) => Action::EnterFullPreview,
            (KeyCode::Enter, _) => Action::Select,
            (KeyCode::Char('p'), KeyModifiers::NONE) => Action::TogglePin,
            (KeyCode::Char('K'), KeyModifiers::NONE | KeyModifiers::SHIFT) | (KeyCode::Char('k'), KeyModifiers::SHIFT) | (KeyCode::Up, KeyModifiers::SHIFT) => Action::MovePinUp,
            (KeyCode::Char('J'), KeyModifiers::NONE | KeyModifiers::SHIFT) | (KeyCode::Char('j'), KeyModifiers::SHIFT) | (KeyCode::Down, KeyModifiers::SHIFT) => Action::MovePinDown,
            (KeyCode::Char('x'), _) => Action::Kill,
            (KeyCode::Char('R'), KeyModifiers::NONE | KeyModifiers::SHIFT) | (KeyCode::Char('r'), KeyModifiers::SHIFT) => Action::Refresh,
            (KeyCode::Char('r'), _) => Action::StartRename,
            (KeyCode::Char('/'), _) => Action::EnterFilter,
            (KeyCode::Char(c @ '0'..='9'), _) => Action::SelectIndex((c as u8 - b'0') as usize),
            (KeyCode::Char(c @ 'a'..='z'), KeyModifiers::ALT) => {
                Action::SelectIndex(10 + (c as u8 - b'a') as usize)
            }
            _ => Action::None,
        },
        Mode::Confirming => match key.code {
            KeyCode::Enter => Action::ConfirmKill,
            KeyCode::Esc => Action::CancelKill,
            _ => Action::None,
        },
        Mode::Filtering => match (key.code, key.modifiers) {
            (KeyCode::Esc, _) => Action::ExitFilter,
            (KeyCode::Enter, _) => Action::Select,
            (KeyCode::Up, _) | (KeyCode::Char('p'), KeyModifiers::CONTROL) => Action::MoveUp,
            (KeyCode::Down, _) | (KeyCode::Char('n'), KeyModifiers::CONTROL) => Action::MoveDown,
            (KeyCode::Char('a'), KeyModifiers::CONTROL) => Action::FilterCursorStart,
            (KeyCode::Char('e'), KeyModifiers::CONTROL) => Action::FilterCursorEnd,
            (KeyCode::Char('u'), KeyModifiers::CONTROL) | (KeyCode::Backspace, KeyModifiers::SUPER) => Action::FilterKillLine,
            (KeyCode::Char('k'), KeyModifiers::CONTROL) => Action::FilterKillLineForward,
            (KeyCode::Char('b'), KeyModifiers::CONTROL) | (KeyCode::Left, KeyModifiers::NONE) => Action::FilterCursorLeft,
            (KeyCode::Char('f'), KeyModifiers::CONTROL) | (KeyCode::Right, KeyModifiers::NONE) => Action::FilterCursorRight,
            (KeyCode::Left, KeyModifiers::ALT) => Action::FilterCursorWordLeft,
            (KeyCode::Right, KeyModifiers::ALT) => Action::FilterCursorWordRight,
            (KeyCode::Backspace, KeyModifiers::ALT) => Action::FilterKillWord,
            (KeyCode::Backspace, _) => Action::FilterBackspace,
            (KeyCode::Delete, _) => Action::FilterDeleteForward,
            (KeyCode::Char(c), _) if c.is_ascii_graphic() || c == ' ' => Action::FilterChar(c),
            _ => Action::None,
        },
        Mode::Renaming => match (key.code, key.modifiers) {
            (KeyCode::Esc, _) => Action::CancelRename,
            (KeyCode::Enter, _) => Action::ConfirmRename,
            (KeyCode::Char('a'), KeyModifiers::CONTROL) => Action::RenameCursorStart,
            (KeyCode::Char('e'), KeyModifiers::CONTROL) => Action::RenameCursorEnd,
            (KeyCode::Char('u'), KeyModifiers::CONTROL) | (KeyCode::Backspace, KeyModifiers::SUPER) => Action::RenameKillLine,
            (KeyCode::Char('k'), KeyModifiers::CONTROL) => Action::RenameKillLineForward,
            (KeyCode::Char('b'), KeyModifiers::CONTROL) | (KeyCode::Left, KeyModifiers::NONE) => Action::RenameCursorLeft,
            (KeyCode::Char('f'), KeyModifiers::CONTROL) | (KeyCode::Right, KeyModifiers::NONE) => Action::RenameCursorRight,
            (KeyCode::Left, KeyModifiers::ALT) => Action::RenameCursorWordLeft,
            (KeyCode::Right, KeyModifiers::ALT) => Action::RenameCursorWordRight,
            (KeyCode::Backspace, KeyModifiers::ALT) => Action::RenameKillWord,
            (KeyCode::Backspace, _) => Action::RenameBackspace,
            (KeyCode::Delete, _) => Action::RenameDeleteForward,
            (KeyCode::Char(c), _) if c.is_ascii_graphic() || c == ' ' => Action::RenameChar(c),
            _ => Action::None,
        },
        Mode::Previewing => match (key.code, key.modifiers) {
            (KeyCode::Esc, _) => Action::ExitFullPreview,
            (KeyCode::Char('h'), _) | (KeyCode::Left, _) => Action::PreviewPrev,
            (KeyCode::Char('l'), _) | (KeyCode::Right, _) => Action::PreviewNext,
            (KeyCode::Enter, _) => Action::SelectPreviewPane,
            _ => Action::None,
        },
    }
}
